[package]
name = "koakuma-common"
version = "0.1.0"
edition = "2018"


[dependencies]
tracing = ">=0.1"
tracing-futures = ">=0.2"
structopt = "0.3.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rmp-serde = "0.15.4"
diesel = { version = "1.4.4", features = ["postgres"] }
